correlation_save_path: correlation.csv
differenced_plot_path: differenced_overlap_accuracy_plot.png
grad_files_in_zip:
- overlap_parameters_tickets/union/overlap_parameters_tickets_target_percentage_0.05_pruning_rounds_10
- overlap_parameters_tickets/union/overlap_parameters_tickets_target_percentage_0.1_pruning_rounds_5
- overlap_parameters_tickets/union/overlap_parameters_tickets_target_percentage_0.2_pruning_rounds_3
imp_plot_path: importance_overlap_plot
last_saved_plot: importance_overlap_plot
output_file_path: extracted_contents.pkl
overlap_accuracy_plot_path: overlap_accuracy_plot.png
results_zip_path: results.zip
smoothed_test_accuracy_plot_path: smoothed_test_accuracy_plot.png
task_performance_file: results/lop/10epochs/task_performance
window_size: 5
winning_tickets_overlap_files:
- results/winning_tickets_masks/target_percentage_0.05_pruning_rounds_10
- results/winning_tickets_masks/target_percentage_0.1_pruning_rounds_5
- results/winning_tickets_masks/target_percentage_0.2_pruning_rounds_3
zip_file_path: results.zip
zip_file_plasticity_exp_path: overlap_parameters_tickets.zip
