general:
  seed: 42
  dataset: 'mnist'
  num_epochs: 10
  batch_size: 32
  lr: 0.001

lop:
  num_tasks: 501
  save_freq: 50

winning_tickets_masks:
  models_dir: ''
  num_tickets: 10
  pairwise: True
  target_percentage: 0.2
  pruning_rounds: 5
  