general:
  id: 1
  seed: 42
  dataset: mnist
  num_epochs: 10
  batch_size: 32
  lr: 0.001
  optimizer: adam
  criterion: cross entropy

lop_experiment:
  num_tasks: 500
  save_freq: 50
  save_folder: ./results/lop_experiment/

winning_tickets_masks:
  models_dir: ./results/lop_experiment/
  num_tickets: 2
  pairwise: true
  target_percentage: 0.5
  pruning_rounds: 2
  tasks: [0, 1]
  #tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
  save_folder: ./results/winning_tickets_masks/

overlap_parameters_tickets:
  masks_dir: ./results/winning_tickets_masks/masks/
  gradients_dir: ./results/parameter_plasticity/
  mask_selection_criterion: first
  save_folder: ./results/overlap_parameters_tickets/first/
  tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
  target_percentages_values: [0.2, 0.1, 0.05]
  pruning_rounds_values: [3, 5, 10]

winning_tickets_plasticity:
  models_dir: ./results/lop_experiment/
  masks_dir: ./results/winning_tickets_masks/masks/
  target_percentage: 0.05
  pruning_rounds: 10
  num_tasks: 100
  save_folder: ./results/winning_tickets_plasticity/
  tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]

winning_tickets_accuracy:
  models_dir: ./results/lop_experiment/
  masks_dir: ./results/winning_tickets_masks/masks/
  target_percentage: 0.05
  pruning_rounds: 10
  save_folder: ./results/winning_tickets_accuracy/
  tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]

test_random_masks:
  models_dir: ./results/lop_experiment/
  target_percentage: 0.05
  save_folder: ./results/test_random_masks/
  num_masks_per_task: 10
  tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]

parameter_plasticity:
  models_dir: ./results/lop_experiment/
  save_folder: ./results/parameter_plasticity/
  tasks: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]