general:
  id: 1
  seed: 42
  dataset: mnist
  num_epochs: 10
  batch_size: 32
  lr: 0.001
  optimizer: adam
  criterion: cross entropy
lop:
  num_tasks: 501
  save_freq: 50
winning_tickets_masks:
  models_dir: ./results/lop/10epochs/
  num_tickets: 10
  pairwise: true
  target_percentage: 0.05
  pruning_rounds: 10
overlap_parameters_tickets:
  masks_dir: ./results/winning_tickets_masks/new_masks/
  gradients_dir: ./results/parameter_plasticity/
  mask_selection_criterion: 'first'
  save_dir: ./results/overlap_parameters_tickets/