general:
  id: 1
  seed: 42
  dataset: mnist
  num_epochs: 1
  batch_size: 32
  lr: 0.001
  optimizer: adam
  criterion: cross entropy
lop:
  num_tasks: 501
  save_freq: 50
winning_tickets_masks:
  models_dir: ./results/lop/10epochs/
  num_tickets: 1
  pairwise: true
  target_percentage: 0.2
  pruning_rounds: 1
